import { useState } from "react";
import { ArrowUpRight, Bell, CheckCircle2, Download, LockKeyhole, Mail, MapPin, Menu, MessageCircle, Phone, Users, Wrench, X, Zap } from "lucide-react";
import { trpc } from "@/lib/trpc";
import { buildStudentLoginInstructionsHtml } from "@shared/studentInstructions";
import { admissionContacts, admissionWhatsAppUrl } from "@shared/admissionContacts";

const assets = {
  logo: "/manus-storage/skill_355b504f.png",
  hero: "/manus-storage/jyoti-picture_0fd2cecc.jpg",
  director: "/manus-storage/director_ee2d2d70.JPG",
  campus: "/manus-storage/classroom_42491fd0.jpeg",
  lab: "/manus-storage/jyotilab_e1ec460d.jpg",
  workshop: "/manus-storage/jyotiworkshop_62d609fe.jpg",
  skillBanner: "/manus-storage/skill-india-banner_a4d9cc64.png",
  skillModal: "/manus-storage/skill-india-modal_d429b319.png",
};

const fallbackNotices = [{ date: "System Notice", type: "Welcome", content: "Welcome to JYOTI ITC! New session details will be updated here." }];
const skillIndiaHomeUrl = "https://www.skillindiadigital.gov.in/home";
const itiResultUrl = "https://dgt.skillindiadigital.gov.in/result";
const detBiharUrl = "https://det.bihar.gov.in/index.html";

function go(role: "student" | "staff" | "admin") {
  window.location.assign(`/portal?role=${role}`);
}

function downloadStudentInstructions() {
  const blob = new Blob([buildStudentLoginInstructionsHtml()], { type: "text/html;charset=utf-8" });
  const url = URL.createObjectURL(blob);
  const anchor = document.createElement("a");
  anchor.href = url;
  anchor.download = "jyoti-itc-student-login-instructions.html";
  anchor.click();
  URL.revokeObjectURL(url);
}

export default function Home() {
  const [mobileOpen, setMobileOpen] = useState(false);
  const [skillIndiaOpen, setSkillIndiaOpen] = useState(false);
  const [skillIndiaActive, setSkillIndiaActive] = useState(false);
  const noticesQuery = trpc.portal.notices.useQuery();
  const notices = noticesQuery.data?.slice(0, 3) ?? fallbackNotices;
  const openSkillIndia = () => { setSkillIndiaActive(true); setSkillIndiaOpen(true); };
  const chooseSkillIndia = (choice: string) => {
    setSkillIndiaActive(true);
    window.open(choice === "ITI Result" ? itiResultUrl : skillIndiaHomeUrl, "_blank", "noopener,noreferrer");
  };

  return (
    <div className="min-h-screen bg-[#f8fafc] text-[#12233d]">
      <header className="border-b-4 border-[#d4ad32] bg-white">
        <div className="mx-auto flex max-w-6xl items-center justify-between gap-6 px-4 py-3 sm:px-6">
          <a href="#top" className="flex items-center gap-3" aria-label="JYOTI ITC home"><img src={assets.logo} alt="Skill India" className="h-12 w-14 object-contain" /><div className="leading-tight"><p className="font-serif text-2xl font-bold tracking-tight">JYOTI ITC</p><p className="text-[11px] font-semibold text-[#4b5563]">Govt. of India | Affiliation: DGET-6/4/71/2010-TC</p><p className="mt-1 inline-block rounded bg-[#12233d] px-2 py-0.5 text-[9px] font-bold tracking-wide text-[#f2c94c]">Developed by Ankit Singh</p></div></a>
          <nav className="hidden items-center gap-2 md:flex"><button onClick={openSkillIndia} className={`rounded-md border px-4 py-2.5 text-sm font-bold transition ${skillIndiaActive ? "border-[#b86b19] bg-[#fff4df] text-[#a14f0b]" : "border-[#12233d]/20 bg-white text-[#12233d] hover:border-[#d4ad32]"}`} aria-pressed={skillIndiaActive}>Skill India</button><a href="#admission" className="rounded-md px-3 py-2 text-sm font-bold text-[#12233d] hover:text-[#c59516]">Admission</a><a href="#contact" className="rounded-md px-3 py-2 text-sm font-bold text-[#12233d] hover:text-[#c59516]">Contact</a><PortalButton label="Student Login" onClick={() => go("student")} /><PortalButton label="Staff Login" onClick={() => go("staff")} /><PortalButton label="Admin Login" onClick={() => go("admin")} accent /><a href={detBiharUrl} target="_blank" rel="noreferrer" className="rounded-md border border-[#b86b19] bg-[#fff4df] px-4 py-2.5 text-sm font-bold text-[#a14f0b] hover:bg-[#f7dfbb]">DET Bihar Admission</a></nav>
          <button className="rounded-md border border-[#12233d]/20 p-2 md:hidden" onClick={() => setMobileOpen((value) => !value)} aria-label="Toggle navigation">{mobileOpen ? <X size={20} /> : <Menu size={20} />}</button>
        </div>
        {mobileOpen && <div className="border-t border-[#12233d]/10 px-4 py-4 md:hidden"><div className="grid gap-2"><button onClick={openSkillIndia} className={`rounded-md border px-3 py-2 text-left text-sm font-bold ${skillIndiaActive ? "border-[#b86b19] bg-[#fff4df] text-[#a14f0b]" : "border-[#12233d]/15"}`}>Skill India</button><a href="#admission" className="rounded-md px-3 py-2 text-sm font-bold" onClick={() => setMobileOpen(false)}>Admission enquiry</a><a href="#contact" className="rounded-md px-3 py-2 text-sm font-bold" onClick={() => setMobileOpen(false)}>Contact details</a><PortalButton label="Student Login" onClick={() => go("student")} /><PortalButton label="Staff Login" onClick={() => go("staff")} /><PortalButton label="Admin Login" onClick={() => go("admin")} accent /><a href={detBiharUrl} target="_blank" rel="noreferrer" className="rounded-md border border-[#b86b19] bg-[#fff4df] px-3 py-2 text-sm font-bold text-[#a14f0b]">DET Bihar Admission</a></div></div>}
      </header>

      <main id="top" className="mx-auto max-w-6xl px-4 sm:px-6">
        <section className="relative mt-5 overflow-hidden rounded-xl border border-[#12233d]/10 bg-white shadow-md"><button type="button" onClick={openSkillIndia} className="block w-full text-left" aria-label="Open Skill India access options"><img src={assets.skillBanner} alt="Skill India banner" className="h-auto w-full object-cover" /></button><div className="flex items-center justify-between border-t border-[#12233d]/10 bg-white px-4 py-2"><span className="text-xs font-bold uppercase tracking-[0.16em] text-[#12233d]/60">Skill India Digital Hub</span><button type="button" onClick={openSkillIndia} className={`rounded-full px-4 py-1.5 text-xs font-bold transition ${skillIndiaActive ? "bg-[#b86b19] text-white" : "bg-[#fff1dc] text-[#a14f0b] hover:bg-[#f7dfbb]"}`}>{skillIndiaActive ? "Active" : "Open"}</button></div></section>

        <section className="relative mt-7 overflow-hidden rounded-xl bg-[#12233d] px-5 py-16 text-center shadow-xl sm:px-10 lg:py-20"><img src={assets.hero} alt="JYOTI ITC workshop" className="absolute inset-0 h-full w-full object-cover opacity-25" /><div className="absolute inset-0 bg-[#12233d]/75" /><div className="relative mx-auto max-w-4xl"><h1 className="font-serif text-4xl font-bold leading-tight text-[#e2b938] sm:text-5xl lg:text-6xl">Shaping Careers, Building the Nation</h1><p className="mx-auto mt-5 max-w-3xl text-base leading-7 text-white/90 sm:text-lg">Welcome to Bihar&apos;s premier technical institute. We provide industry-aligned training, state-of-the-art workshops, and 100% placement support to secure your bright future.</p><div className="mt-8 grid gap-4 sm:grid-cols-3">{[["1500+", "Alumni Placed"], ["100%", "Job Assistance"], ["20+", "Expert Instructors"]].map(([value, label], index) => <div key={label} className={`rounded-lg border ${index === 1 ? "border-[#e2b938] bg-[#e2b938]/10" : "border-white/25 bg-white/10"} px-4 py-6`}><p className="text-3xl font-bold text-[#e2b938]">{value}</p><p className="mt-2 text-xs font-bold uppercase tracking-wide text-white">{label}</p></div>)}</div></div></section>

        <section id="trades" className="py-10"><SectionTitle>Explore Premium Trades</SectionTitle><div className="grid gap-6 md:grid-cols-2"><TradeCard icon={<Wrench size={22} />} title="Fitter (NSQF Level 5)" border="border-l-[#12233d]" description="Master mechanical assembling, precision measurement, lathe operations, and advanced welding techniques. Perfect for heavy industries and manufacturing sectors." /><TradeCard icon={<Zap size={22} />} title="Electrician (NSQF Level 5)" border="border-l-[#d4ad32]" description="Learn industrial wiring, AC/DC motor winding, power distribution, and fault troubleshooting. Extremely high demand globally in all power sectors." /></div></section>

        <section id="placement" className="pb-10"><SectionTitle>Admissions, Fees &amp; Placement</SectionTitle><div className="grid gap-5 md:grid-cols-3"><InfoCard title="Admission fee" value="₹30,000" text="Initial admission and registration fee. Ask the admission desk for the current session payment schedule." accent="navy" /><InfoCard title="Course duration" value="2 years" text="Government-aligned Fitter and Electrician training with practical workshop exposure." accent="gold" /><InfoCard title="Placement support" value="100% assistance" text="Interview preparation, employer coordination, and job-assistance guidance for eligible trainees." accent="green" /></div><div className="mt-5 grid gap-3 rounded-xl border border-[#d4ad32]/40 bg-[#fffdf3] p-5 sm:grid-cols-2"><div className="flex items-start gap-3"><CheckCircle2 className="mt-1 text-[#2f7d59]" size={19} /><p className="text-sm leading-6"><b>Placement readiness:</b> practical skill development, attendance discipline, and interview preparation.</p></div><div className="flex items-start gap-3"><CheckCircle2 className="mt-1 text-[#2f7d59]" size={19} /><p className="text-sm leading-6"><b>Industry direction:</b> manufacturing, electrical maintenance, construction, and service-sector opportunities.</p></div></div></section>

        <section id="campus" className="pb-10"><SectionTitle>Campus Updates &amp; Info</SectionTitle><div className="grid gap-6 lg:grid-cols-[1fr_1.15fr]"><div className="rounded-xl border border-[#12233d]/10 bg-white p-6 shadow-sm"><div className="flex items-center gap-3 border-b border-[#12233d]/10 pb-4"><div className="grid h-10 w-10 place-items-center rounded-full bg-[#f8e8a6] text-[#12233d]"><Bell size={19} /></div><h2 className="font-serif text-2xl font-bold">Digital Notice Board</h2></div><div className="notice-marquee" aria-label="Scrolling notices"><div className="notice-marquee-track divide-y divide-[#12233d]/10">{noticesQuery.isLoading && <p className="py-5 text-sm text-slate-500">Loading notices…</p>}{[0, 1].flatMap((copy) => notices.map((notice, index) => <article key={`${copy}-${notice.date}-${index}`} className="py-5"><p className="text-xs font-bold text-[#d09f1f]">{notice.date} · {notice.type}</p><h3 className="mt-2 font-semibold">{notice.content.split("\n")[0]}</h3><p className="mt-1 text-sm leading-6 text-slate-600">{notice.content}</p></article>))}</div></div></div><div className="grid gap-5 rounded-xl bg-[#eef2f6] p-5 sm:grid-cols-[160px_1fr] sm:items-center"><img src={assets.director} alt="Sandeep Kumar, Managing Director" className="h-44 w-full rounded-lg object-cover sm:h-48" /><div><p className="text-xs font-bold uppercase tracking-widest text-[#d09f1f]">Director&apos;s message</p><h2 className="mt-2 font-serif text-3xl font-bold">Sandeep Kumar</h2><p className="text-sm font-semibold text-slate-500">Managing Director</p><blockquote className="mt-5 text-sm italic leading-6 text-slate-700">“Education is the passport to the future. At JYOTI ITC, we don&apos;t just teach skills; we build confidence and solid careers.”</blockquote></div></div></div></section>

        <section id="admission" className="pb-10"><SectionTitle>Admission Enquiry</SectionTitle><div className="grid gap-6 lg:grid-cols-[0.9fr_1.1fr]"><div className="rounded-xl bg-[#12233d] p-7 text-white"><p className="text-xs font-bold uppercase tracking-[0.22em] text-[#e2b938]">Start your training journey</p><h2 className="mt-3 font-serif text-3xl font-bold text-[#e2b938]">Speak directly with the admission desk</h2><p className="mt-4 text-sm leading-7 text-white/75">For admission, fees, documents, trade selection, and current session details, call us directly or send a WhatsApp message. Our team will attend your enquiry personally.</p><button onClick={downloadStudentInstructions} className="mt-7 inline-flex items-center gap-2 rounded-md border border-[#e2b938] px-4 py-3 text-sm font-bold text-[#e2b938] hover:bg-[#e2b938] hover:text-[#12233d]"><Download size={16} /> Download student login guide</button></div><div className="rounded-xl border border-[#12233d]/10 bg-white p-6 shadow-sm"><p className="text-sm font-semibold uppercase tracking-[0.16em] text-[#c59516]">Admission contact numbers</p><p className="mt-2 text-sm leading-6 text-slate-600">Choose any number below. WhatsApp opens with a ready-to-send professional admission message.</p><div className="mt-5 grid gap-4 sm:grid-cols-2">{admissionContacts.map((contact) => <div key={contact.tel} className="rounded-xl border border-[#12233d]/10 bg-[#f8fafc] p-4"><p className="font-serif text-xl font-bold text-[#12233d]">{contact.display}</p><div className="mt-4 grid gap-2"><a href={`tel:${contact.tel}`} className="inline-flex items-center justify-center gap-2 rounded-md bg-[#12233d] px-4 py-3 text-sm font-bold text-white transition hover:bg-[#20395f]"><Phone size={16} /> Call Now</a><a href={admissionWhatsAppUrl(contact.whatsapp)} target="_blank" rel="noreferrer" className="inline-flex items-center justify-center gap-2 rounded-md bg-[#218c56] px-4 py-3 text-sm font-bold text-white transition hover:bg-[#176a40]"><MessageCircle size={16} /> WhatsApp Enquiry</a></div></div>)}</div><p className="mt-5 rounded-lg border border-[#d4ad32]/40 bg-[#fffdf3] px-4 py-3 text-xs leading-5 text-slate-600">WhatsApp message: “Hello JYOTI ITC Rosera Admission Desk, I would like to enquire about admission…” You can add your name and preferred trade before sending.</p></div></div></section>

        <section id="gallery" className="pb-10"><SectionTitle>Campus Gallery</SectionTitle><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><Gallery image={assets.campus} label="Smart Class" /><Gallery image={assets.lab} label="Lab" /><Gallery image={assets.workshop} label="Workshop" /><Gallery image={assets.hero} label="Campus" /></div></section>
        <section className="mb-10 rounded-xl bg-[#12233d] px-6 py-9 text-center text-white"><h2 className="font-serif text-3xl font-bold text-[#e2b938]">Enterprise Portal Access</h2><p className="mx-auto mt-3 max-w-2xl text-sm text-white/75">Students, staff, and administrators can access their role-specific workspace connected to the official records system.</p><div className="mt-6 flex flex-wrap justify-center gap-3"><button onClick={() => go("student")} className="rounded-md bg-white px-5 py-3 text-sm font-bold text-[#12233d]">Student Login</button><button onClick={downloadStudentInstructions} className="inline-flex items-center gap-2 rounded-md border border-white/30 px-5 py-3 text-sm font-bold text-white"><Download size={15} /> Login guide</button><button onClick={() => go("admin")} className="rounded-md border border-[#e2b938] px-5 py-3 text-sm font-bold text-[#e2b938]"><LockKeyhole size={15} className="mr-2 inline" />Admin Login</button></div></section>
      </main>

      {skillIndiaOpen && <div className="fixed inset-0 z-50 grid place-items-center bg-[#0b1424]/75 p-4" role="dialog" aria-modal="true" aria-labelledby="skill-india-dialog-title"><div className="relative max-h-[90vh] w-full max-w-3xl overflow-auto rounded-2xl bg-white p-5 shadow-2xl sm:p-8"><button type="button" onClick={() => setSkillIndiaOpen(false)} className="absolute right-4 top-4 rounded-full p-2 text-2xl leading-none text-[#12233d]/60 hover:bg-[#f1f4f7]" aria-label="Close Skill India options">×</button><div className="flex items-center gap-3 border-b border-[#12233d]/10 pb-5"><img src={assets.logo} alt="Skill India" className="h-11 w-14 object-contain" /><div><p className="text-xs font-bold uppercase tracking-[0.18em] text-[#b86b19]">Skill India Digital Hub</p><h2 id="skill-india-dialog-title" className="mt-1 font-serif text-2xl font-bold text-[#12233d] sm:text-3xl">Welcome to Skill India</h2></div></div><p className="mt-5 text-center text-sm text-slate-600">Choose an access option to continue directly to the relevant JYOTI ITC portal workspace.</p><div className="mt-6 grid gap-4 sm:grid-cols-2">{[{ title: "Learner/Participant", text: "Open the official Skill India Digital Hub for learner and participant services.", action: "Open Skill India" }, { title: "Partner", text: "Open the official Skill India Digital Hub partner services.", action: "Open Skill India" }, { title: "DGT Ecosystem", text: "Open the official Skill India Digital Hub DGT ecosystem services.", action: "Open Skill India" }, { title: "ITI Result", text: "Open the official DGT Skill India result portal for ITI results.", action: "Open Official Result" }].map((item) => <button type="button" key={item.title} onClick={() => chooseSkillIndia(item.title)} className="rounded-xl border border-[#12233d]/15 bg-white p-5 text-left shadow-sm transition hover:-translate-y-0.5 hover:border-[#d4ad32] hover:bg-[#fffdf4]"><p className="font-serif text-xl font-bold text-[#12233d]">{item.title}</p><p className="mt-2 min-h-10 text-sm leading-6 text-slate-600">{item.text}</p><span className="mt-4 inline-flex rounded-md bg-[#12233d] px-3 py-2 text-xs font-bold text-white">{item.action}</span></button>)}</div><p className="mt-6 text-center text-xs text-slate-500">By continuing, you agree to use the official JYOTI ITC access workspace.</p></div></div>}

      <footer id="contact" className="border-t-4 border-[#d4ad32] bg-[#12233d] text-white"><div className="mx-auto grid max-w-6xl gap-7 px-4 py-9 sm:px-6 md:grid-cols-3"><div><p className="font-serif text-2xl font-bold text-[#e2b938]">JYOTI ITC</p><p className="mt-2 text-sm leading-6 text-white/70">Government-affiliated technical training for confident careers in Fitter and Electrician trades.</p></div><div><p className="text-xs font-bold uppercase tracking-[0.2em] text-[#e2b938]">Contact details</p><p className="mt-3 flex items-start gap-2 text-sm text-white/80"><MapPin size={17} className="mt-0.5 shrink-0" />Rosera, Samastipur, Bihar</p><p className="mt-2 flex items-center gap-2 text-sm text-white/80"><Phone size={17} /><span>Admission: <a href="tel:+919709506515" className="hover:text-[#e2b938]">+91 97095 06515</a> · <a href="tel:+91797997374" className="hover:text-[#e2b938]">+91 79799 7374</a></span></p><p className="mt-2 flex items-center gap-2 text-sm text-white/80"><Mail size={17} />Email: jyotiitc.rosera@gmail.com</p></div><div><p className="text-xs font-bold uppercase tracking-[0.2em] text-[#e2b938]">Quick access</p><div className="mt-3 grid gap-2 text-sm"><a href="#admission" className="text-white/80 hover:text-[#e2b938]">Admission enquiry</a><a href="#placement" className="text-white/80 hover:text-[#e2b938]">Fees and placement</a><a href="#top" className="text-white/80 hover:text-[#e2b938]">Back to top</a></div></div></div><div className="border-t border-white/10 px-4 py-4 text-center text-xs text-white/50">© 2026 JYOTI ITC Rosera · Affiliation: DGET-6/4/71/2010-TC</div></footer>
    </div>
  );
}

function PortalButton({ label, onClick, accent = false }: { label: string; onClick: () => void; accent?: boolean }) { return <button onClick={onClick} className={`rounded-md border px-5 py-2.5 text-sm font-bold transition ${accent ? "border-[#d4ad32] bg-[#e2b938] text-[#12233d] hover:bg-[#f2c94c]" : "border-[#12233d]/25 bg-white text-[#12233d] hover:border-[#d4ad32]"}`}>{label}</button>; }
function SectionTitle({ children }: { children: React.ReactNode }) { return <h2 className="mb-5 border-l-4 border-[#d4ad32] pl-3 font-serif text-2xl font-bold text-[#12233d] sm:text-3xl">{children}</h2>; }
function Field({ label, children }: { label: string; children: React.ReactNode }) { return <label className="space-y-2 text-xs font-bold uppercase tracking-wider text-[#12233d]/55"><span className="block">{label}</span>{children}</label>; }
function TradeCard({ icon, title, description, border }: { icon: React.ReactNode; title: string; description: string; border: string }) { return <article className={`rounded-lg border border-[#12233d]/10 border-l-4 ${border} bg-white p-6 shadow-sm transition hover:-translate-y-1 hover:shadow-md`}><h3 className="flex items-center gap-3 font-serif text-xl font-bold">{icon}{title}</h3><p className="mt-4 text-sm leading-6 text-slate-600">{description}</p><p className="mt-5 inline-block bg-[#f8fafc] px-3 py-2 text-xs font-bold">Duration: 2 Yrs | Eligibility: 10th Pass</p></article>; }
function InfoCard({ title, value, text, accent }: { title: string; value: string; text: string; accent: "navy" | "gold" | "green" }) { const colors = { navy: "border-l-[#12233d]", gold: "border-l-[#d4ad32]", green: "border-l-[#2f7d59]" }; return <article className={`rounded-xl border border-[#12233d]/10 border-l-4 ${colors[accent]} bg-white p-6 shadow-sm`}><p className="text-xs font-bold uppercase tracking-[0.14em] text-slate-500">{title}</p><p className="mt-3 font-serif text-3xl font-bold text-[#12233d]">{value}</p><p className="mt-3 text-sm leading-6 text-slate-600">{text}</p></article>; }
function Gallery({ image, label }: { image: string; label: string }) { return <figure className="group overflow-hidden rounded-lg border border-[#12233d]/10 bg-white shadow-sm"><img src={image} alt={label} className="h-48 w-full object-cover transition duration-500 group-hover:scale-105" /><figcaption className="px-4 py-3 text-sm font-bold">{label}</figcaption></figure>; }
